mod db "./config/scripts/db.just"
mod generate "./config/scripts/generate.just"
mod setup "./config/scripts/setup.just"
mod start "./config/scripts/start.just"
mod stop "./config/scripts/stop.just"
mod test "./config/scripts/test.just"
mod create "./config/scripts/create.just"