name: pathlight_workspace
description: The Workspace for the Pathlight project.
version: 1.0.0

publish_to: none
environment:
  sdk: ^3.11.0

dependencies: 
  freezed_annotation: ^3.1.0  
  oidc: ^0.14.0
  oidc_default_store: ^0.6.0
  auto_route: ^11.1.0
dev_dependencies:
  auto_route_generator: ^10.5.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
  dart_arch_test: ^0.3.1
  flutter_test:
    sdk: flutter
  
workspace:
  - domain/todo/frontend
  - domain/auth/frontend
  - app/client/pathlight
  - domain/shared/flutter_rust
  - domain/shared/state_machine/flutter