name: pathlight
description: The Workspace for the Pathlight project.
version: 1.0.0

publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - domain/shared/flutter_rust
  - domain/todo/frontend
  - domain/shared/state_machine/flutter

dependencies: 
  freezed_annotation: ^3.1.0  
dev_dependencies:
  melos: ^7.5.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
