[server]
address = "0.0.0.0:50051"

[database]
url = "postgres://pathlight:PathlightSecurePassword123!@localhost:5432/pathlight"

[admin_db]
url = "postgres://postgres:postgresPassword!@localhost:5432/pathlight"


[website]
url = "http://localhost:4444"
